### ISSUE TITLE
코드 스타일에 맞게 코드 수정 중입니다.

### ISSUE THREAD

**Issue by whereful** [qazxsw1240/React-Team-Project#10]
- 들여쓰기
- 변수명
- 익명 함수, 화살표 함수 등
- 알림창 디자인 수정

**Comment by qazxsw1240** [comment]
제 작업 영역이 수정돼 있어서 최대한 빨리 이 이슈를 병합해야 합니다. 작업이 완료됐으면 PR해 주세요
