### ISSUE TITLE
북마크 추가 창 디자인 수정 및 추가 시 메인 화면에 반영 

### ISSUE THREAD

**Issue by whereful** [qazxsw1240/React-Team-Project#22]
- 북마크 추가 창의 input 태그 높이 조정 필요
- 북마크 추가 설명 div에서 글자 여백 조정 필요
- 북마크 추가 완료 시 메인 화면에 반영 필요

**Comment by qazxsw1240** [comment]
ModifiableInput 컴포넌트 changeText 함수 내에 `props.bookmark[props.category] = event.target.value;` 식 제거 부탁합니다.
